/**
 * @module ol/render/webgl/circlereplay/defaultshader/Locations
 */
// This file is automatically generated, do not edit
// Run `make shaders` to generate, and commit the result.

import { DEBUG_WEBGL } from '../../../../index';

/**
 * @constructor
 * @param {WebGLRenderingContext} gl GL.
 * @param {WebGLProgram} program Program.
 * @struct
 */
export default class Locations {
	public u_projectionMatrix: WebGLUniformLocation;
	public u_offsetScaleMatrix: WebGLUniformLocation;
	public u_offsetRotateMatrix: WebGLUniformLocation;
	public u_lineWidth: WebGLUniformLocation;
	public u_pixelRatio: WebGLUniformLocation;
	public u_opacity: WebGLUniformLocation;
	public u_fillColor: WebGLUniformLocation;
	public u_strokeColor: WebGLUniformLocation;
	public u_size: WebGLUniformLocation;
	public a_position: number;
	public a_instruction: number;
	public a_radius: number;
	constructor(gl: WebGLRenderingContext, program: WebGLProgram) {

		/**
		 * @type {WebGLUniformLocation}
		 */
		this.u_projectionMatrix = gl.getUniformLocation(
			program, DEBUG_WEBGL ? 'u_projectionMatrix' : 'h');

		/**
		 * @type {WebGLUniformLocation}
		 */
		this.u_offsetScaleMatrix = gl.getUniformLocation(
			program, DEBUG_WEBGL ? 'u_offsetScaleMatrix' : 'i');

		/**
		 * @type {WebGLUniformLocation}
		 */
		this.u_offsetRotateMatrix = gl.getUniformLocation(
			program, DEBUG_WEBGL ? 'u_offsetRotateMatrix' : 'j');

		/**
		 * @type {WebGLUniformLocation}
		 */
		this.u_lineWidth = gl.getUniformLocation(
			program, DEBUG_WEBGL ? 'u_lineWidth' : 'k');

		/**
		 * @type {WebGLUniformLocation}
		 */
		this.u_pixelRatio = gl.getUniformLocation(
			program, DEBUG_WEBGL ? 'u_pixelRatio' : 'l');

		/**
		 * @type {WebGLUniformLocation}
		 */
		this.u_opacity = gl.getUniformLocation(
			program, DEBUG_WEBGL ? 'u_opacity' : 'm');

		/**
		 * @type {WebGLUniformLocation}
		 */
		this.u_fillColor = gl.getUniformLocation(
			program, DEBUG_WEBGL ? 'u_fillColor' : 'n');

		/**
		 * @type {WebGLUniformLocation}
		 */
		this.u_strokeColor = gl.getUniformLocation(
			program, DEBUG_WEBGL ? 'u_strokeColor' : 'o');

		/**
		 * @type {WebGLUniformLocation}
		 */
		this.u_size = gl.getUniformLocation(
			program, DEBUG_WEBGL ? 'u_size' : 'p');

		/**
		 * @type {number}
		 */
		this.a_position = gl.getAttribLocation(
			program, DEBUG_WEBGL ? 'a_position' : 'e');

		/**
		 * @type {number}
		 */
		this.a_instruction = gl.getAttribLocation(
			program, DEBUG_WEBGL ? 'a_instruction' : 'f');

		/**
		 * @type {number}
		 */
		this.a_radius = gl.getAttribLocation(
			program, DEBUG_WEBGL ? 'a_radius' : 'g');
	}
}
